name = "eliteconsult-website"
type = "javascript"
compatibility_date = "2026-02-15"

[env.production]
name = "eliteconsult-website"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src", "app", "components", "lib", "public"]

[[env.production.routes]]
pattern = "*"
zone_name = "eliteconsult.work"

[site]
bucket = ".next/static"

[triggers.crons]

[observability]
enabled = true
